# WeatherSight - Supabase Environment Setup Script
# This script helps you configure your Supabase credentials

Write-Host "=======================================" -ForegroundColor Cyan
Write-Host "  WeatherSight - Supabase Setup" -ForegroundColor Cyan
Write-Host "=======================================" -ForegroundColor Cyan
Write-Host ""

# Check if .env.local already exists
$envPath = Join-Path $PSScriptRoot ".env.local"
if (Test-Path $envPath) {
    Write-Host "⚠️  .env.local file already exists!" -ForegroundColor Yellow
    $overwrite = Read-Host "Do you want to overwrite it? (y/n)"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Host "Setup cancelled." -ForegroundColor Red
        exit
    }
}

Write-Host ""
Write-Host "Please enter your Supabase credentials:" -ForegroundColor Green
Write-Host "(You can find these in your Supabase Project Settings > API)" -ForegroundColor Gray
Write-Host ""

# Get Supabase URL
Write-Host "Enter your Supabase Project URL:" -ForegroundColor Yellow
Write-Host "(Example: https://xxxxxxxxxxxxx.supabase.co)" -ForegroundColor Gray
$supabaseUrl = Read-Host "URL"

# Validate URL format
if ($supabaseUrl -notmatch "^https://.*\.supabase\.co$") {
    Write-Host "⚠️  Warning: URL doesn't look like a valid Supabase URL" -ForegroundColor Yellow
    Write-Host "Expected format: https://xxxxxxxxxxxxx.supabase.co" -ForegroundColor Gray
    $continue = Read-Host "Continue anyway? (y/n)"
    if ($continue -ne "y" -and $continue -ne "Y") {
        Write-Host "Setup cancelled." -ForegroundColor Red
        exit
    }
}

Write-Host ""

# Get Supabase Anon Key
Write-Host "Enter your Supabase Anon Key (public key):" -ForegroundColor Yellow
Write-Host "(Example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...)" -ForegroundColor Gray
$supabaseKey = Read-Host "Anon Key"

# Validate key format (should be a JWT token)
if ($supabaseKey -notmatch "^eyJ") {
    Write-Host "⚠️  Warning: Key doesn't look like a valid JWT token" -ForegroundColor Yellow
    Write-Host "Expected format: Should start with 'eyJ'" -ForegroundColor Gray
    $continue = Read-Host "Continue anyway? (y/n)"
    if ($continue -ne "y" -and $continue -ne "Y") {
        Write-Host "Setup cancelled." -ForegroundColor Red
        exit
    }
}

Write-Host ""
Write-Host "Creating .env.local file..." -ForegroundColor Cyan

# Create the .env.local file
$envContent = @"
# Supabase Configuration
# Generated by setup-env.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

NEXT_PUBLIC_SUPABASE_URL=$supabaseUrl
NEXT_PUBLIC_SUPABASE_ANON_KEY=$supabaseKey
"@

$envContent | Out-File -FilePath $envPath -Encoding utf8 -Force

Write-Host "✅ .env.local file created successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "1. Run the SQL setup script in your Supabase dashboard" -ForegroundColor White
Write-Host "   (See SUPABASE_SETUP_GUIDE.md for instructions)" -ForegroundColor Gray
Write-Host "2. Restart your development server" -ForegroundColor White
Write-Host "   npm run dev" -ForegroundColor Gray
Write-Host "3. Test the sign-up functionality" -ForegroundColor White
Write-Host ""
Write-Host "Press any key to exit..."
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")

